/**
 * Sync design tokens from src/shared/theme.css into the shadow-DOM stylesheet
 * src/content/ui-styles.js.
 * ------------------------------------------------------------------
 * The panel lives in a closed shadow root and cannot <link> a stylesheet, so
 * its tokens must be inlined. theme.css is the single source; this tool copies
 * the custom-property declarations between managed markers. It also renames the
 * legacy c- / sp- / r- tokens in the panel rule bodies to the --sr-* names so
 * the panel references the same values as popup/options.
 *
 * It refuses to invent values: if a legacy token has no mapping it reports it.
 */
import { readFileSync, writeFileSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const HERE = path.dirname(fileURLToPath(import.meta.url));
const ROOT = path.resolve(HERE, '..');
const THEME = path.join(ROOT, 'src/shared/theme.css');
const UI = path.join(ROOT, 'src/content/ui-styles.js');

const START = '/* tokens:start - generated by tools/sync-theme.mjs, do not edit */';
const END = '/* tokens:end */';

// legacy panel token -> canonical --sr-* token
const ALIAS = {
  '--c-bg': '--sr-glass',
  '--c-bg-2': '--sr-surface-2',
  '--c-bg-3': '--sr-surface',
  '--c-fg': '--sr-ink',
  '--c-fg-2': '--sr-ink-2',
  '--c-line': '--sr-line',
  '--c-line-2': '--sr-line-2',
  '--c-accent': '--sr-accent',
  '--c-accent-soft': '--sr-accent-soft',
  '--c-mint': '--sr-ok',
  '--c-ok': '--sr-ok',
  '--c-warn': '--sr-warn',
  '--c-err': '--sr-err',
  '--c-shadow': '--sr-shadow-2',
  '--c-shadow-soft': '--sr-shadow-1',
  '--c-inset-hi': '--sr-inset',
  '--sp-1': '--sr-sp-1',
  '--sp-2': '--sr-sp-2',
  '--sp-3': '--sr-sp-3',
  '--sp-4': '--sr-sp-4',
  '--sp-5': '--sr-sp-5',
  '--r-sm': '--sr-r-1',
  '--r-md': '--sr-r-2',
  '--r-lg': '--sr-r-3',
  '--r-pill': '--sr-r-pill',
  '--t-fast': '--sr-t-fast',
  '--t-mid': '--sr-t-mid',
  '--t-slow': '--sr-t-slow',
  '--ease-out': '--sr-ease',
  '--ease-spring': '--sr-spring',
  '--font': '--sr-font',
  '--mono': '--sr-mono',
};

/** Extract all `--name: value;` declarations from a CSS string. */
function declarations(css) {
  const out = [];
  for (const m of css.matchAll(/(--[a-z0-9-]+)\s*:\s*([^;]+);/gi)) {
    out.push(`  ${m[1]}: ${m[2].trim()};`);
  }
  return out;
}

/** Split theme.css into shared (light) and dark declaration sets. */
function readTheme() {
  const css = readFileSync(THEME, 'utf8');
  const darkStart = css.indexOf("[data-theme='dark']");
  const sharedSrc = darkStart >= 0 ? css.slice(0, darkStart) : css;
  const darkSrc = darkStart >= 0 ? css.slice(darkStart) : '';
  return { light: declarations(sharedSrc), dark: declarations(darkSrc) };
}

/** Replace the body of the rule opened at `selectorIndex` (the '{' there). */
function replaceRuleBlock(src, selector, newInnerLines) {
  const open = src.indexOf('{', src.indexOf(selector));
  if (open < 0) throw new Error('selector not found: ' + selector);
  let depth = 0;
  let close = -1;
  for (let i = open; i < src.length; i++) {
    if (src[i] === '{') depth++;
    else if (src[i] === '}') {
      depth--;
      if (depth === 0) {
        close = i;
        break;
      }
    }
  }
  if (close < 0) throw new Error('unclosed rule for ' + selector);
  const inner = src.slice(open + 1, close);
  const block = '\n' + START + '\n' + newInnerLines.join('\n') + '\n' + END + '\n';
  let nextInner;
  if (inner.includes(START)) {
    nextInner = inner.replace(new RegExp(START.replace(/[.*]/g, m => `\\${m}`) + '[\\s\\S]*?' + END.replace(/[.*]/g, m => `\\${m}`)), block.trim());
  } else {
    // drop legacy custom-property declarations and insert managed block
    const kept = inner
      .split('\n')
      .filter(l => !/^\s*--[a-z0-9-]+\s*:/.test(l))
      .join('\n');
    nextInner = block + kept;
  }
  return src.slice(0, open + 1) + nextInner + src.slice(close);
}

function main() {
  const { light, dark } = readTheme();
  let js = readFileSync(UI, 'utf8');
  js = replaceRuleBlock(js, '.srad-root {', light);
  js = replaceRuleBlock(js, '.srad-root[data-theme="dark"] {', dark);

  // rename legacy token references in rule bodies
  const unknown = new Set();
  js = js.replace(/var\((--[a-z0-9-]+)/g, (full, name) => {
    if (name.startsWith('--sr-')) return full;
    if (ALIAS[name]) return 'var(' + ALIAS[name];
    unknown.add(name);
    return full;
  });

  writeFileSync(UI, js);
  if (unknown.size) {
    console.error('sync-theme: unmapped legacy tokens (panel may fall back):', [...unknown].join(', '));
    process.exit(1);
  }
  console.log('synced ' + light.length + ' light + ' + dark.length + ' dark tokens into src/content/ui-styles.js');
}

main();
